[tool.bumpversion]
current_version = "3.2.1"
commit = true
tag = false
sign_tags = true
tag_name = "{new_version}"
parse = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(((?P<local>\.dev0\+)([0-9a-fA-F]+)))?'
serialize = [
    "{major}.{minor}.{patch}.dev0+{local}{utcnow:%Y%m%d%H%M%S}",
    "{major}.{minor}.{patch}",
]

[tool.bumpversion.part.local]
first_value = "valid"
optional_value = "valid"
values = [
    "valid",
    ".dev0+",
]

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "polyswarm_engine/__init__.py"
search = "__VERSION__ = '{current_version}'"
replace = "__VERSION__ = '{new_version}'"
