include:
  - project: '$CI_TEMPLATE'
    ref: master
    file: '.gitlab-ci-default.yaml'

###############################################################
# Build Stage
###############################################################

dev-pypi:
  extends: .dev-pypi

###############################################################
# Test Stage
###############################################################

test-run38:
  stage: test
  tags:
    - stage-kube-newer
  image: python:3.8
  before_script:
    - pip install -U pip
    - pip install .[tests]
  script:
    - pip install -r requirements.txt
    - PYTHONPATH=. pytest -s -v

test-run39:
  stage: test
  tags:
    - stage-kube-newer
  image: python:3.9
  before_script:
    - pip install -U pip
    - pip install .[tests]
  script:
    - pip install -r requirements.txt
    - PYTHONPATH=. pytest -s -v

test-run310:
  stage: test
  tags:
    - stage-kube-newer
  image: public.ecr.aws/docker/library/python:3.10-slim-buster
  before_script:
    - pip install -U pip
    - pip install .[tests]
  script:
    - pip install -r requirements.txt
    - PYTHONPATH=. pytest -s -v

test-run311:
  stage: test
  tags:
    - stage-kube-newer
  image: python:3.11
  before_script:
    - pip install -U pip
    - pip install .[tests]
  script:
    - pip install -r requirements.txt
    - PYTHONPATH=. pytest -s -v

test-run312:
  stage: test
  tags:
    - stage-kube-newer
  image: python:3.12
  before_script:
    - pip install -U pip
    - pip install .[tests]
  script:
    - pip install -r requirements.txt
    - PYTHONPATH=. pytest -s -v

test-run313:
  stage: test
  tags:
    - stage-kube-newer
  image: python:3.13
  before_script:
    - pip install -U pip
    - pip install .[tests]
  script:
    - pip install -r requirements.txt
    - PYTHONPATH=. pytest -s -v

test-run314:
  stage: test
  tags:
    - stage-kube-newer
  image: python:3.14
  before_script:
    - pip install -U pip
    - pip install .[tests]
  script:
    - pip install -r requirements.txt
    - PYTHONPATH=. pytest -s -v

###############################################################
# Release Stage
###############################################################

release-pypi:
  extends: .release-pypi-public
